<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Utilities\RevitApiCourse.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo Configuration: $(Configuration)&#xD;&#xA;if not exist &quot;%25APPDATA%25\Autodesk\Revit\Addins\2026\$(ProjectName)&quot; mkdir &quot;%25APPDATA%25\Autodesk\Revit\Addins\2026\$(ProjectName)&quot;&#xD;&#xA;copy &quot;$(TargetDir)$(TargetName).dll&quot; &quot;%25APPDATA%25\Autodesk\Revit\Addins\2026\$(ProjectName)&quot;&#xD;&#xA;copy &quot;$(TargetDir)$(TargetName).pdb&quot; &quot;%25APPDATA%25\Autodesk\Revit\Addins\2026\$(ProjectName)&quot;&#xD;&#xA;copy &quot;$(TargetDir)\Utilities\*.addin&quot; &quot;%25APPDATA%25\Autodesk\Revit\Addins\2026&quot;&#xD;&#xA;&#xD;&#xA;start &quot;&quot; &quot;C:\Program Files\Autodesk\Revit 2026\Revit.exe&quot;" />
  </Target>
	
	<PropertyGroup>
		<StartAction>Program</StartAction>
		<StartProgram>C:\Program Files\Autodesk\Revit 2026\Revit.exe</StartProgram>
	</PropertyGroup>
</Project>
